# List of packages to uninstall
removePacman=(
    alacritty  
    vim 
    gvim 
    chromium 
    mpv 
    freerdp 
    mousepad 
    python-pip 
    python-psutil 
    python-rich 
    python-click 
    man-pages 
    nm-connection-editor 
    xdg-desktop-portal 
    pfetch 
    trizen 
    pacseek 
    gtk4 
    libadwaita 
    fuse2 
    papirus-icon-theme 
    breeze-icons
    wlogout
    guvcview 
    imagemagick
    qalculate-gtk
)

packagesPacman=(
    bat 
    cronie 
    kitty
    fd 
    ffmpegthumbnailer 
    fzf 
    less 
    jq 
    thunar-volman 
    thunar-archive-plugin
    ripgrep 
    neofetch 
    noto-fonts-cjk 
    noto-fonts-emoji 
    poppler 
    ttf-jetbrains-mono
    ttf-jetbrains-mono-nerd 
    reflector 
    unarchiver 
    xfce4-settings 
    yazi 
    zoxide 
    zsh 
    zsh-completions 
    zsh-syntax-highlighting 
    gst-plugins-good 
    lollypop
    qt5-wayland
)    

packagesYay=(
    brave-bin 
    cava-git  
    fnm-bin 
    grimblast-git 
    solaar 
    zsh-autocomplete-git 
    paru-bin 
    visual-studio-code-bin 
    
)

packagesDev=(
    docker-compose 
    docker-desktop
)